[package]
name = "ponder"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlite = "0.36.1"
serde_json = "1.0.127"
serde = { version = "1.0.126", features = ["derive"] }
ratatui = "0.28.1"
crossterm = "0.28.1"
